### ISSUE TITLE
Establecer servicios necesarios para el Formulario Proveedor

### ISSUE THREAD

**Issue by TattaArias** [JhonTriana/Poli_CCT#31]
Formulario Proveedor
Atributos:

● Registro de Empleados [Button]
● Cargar Documentos [Button]
● Regresar [Button]

**Comment by NaslyGordi** [comment]
[https://app.zenhub.com/files/244173603/0f5e522f-e6d1-4393-a4c7-e919f5a85905/download](https://app.zenhub.com/files/244173603/0f5e522f-e6d1-4393-a4c7-e919f5a85905/download)
