### ISSUE TITLE
Establecer servicios necesarios para el Formulario Registro Empleados del Proveedor

### ISSUE THREAD

**Issue by TattaArias** [JhonTriana/Poli_CCT#32]
Formulario Registro Empleados del Proveedor
Atributos:

● Nit / Cedula [Label - Texbox]

Acta - reunión de planeación

● Nombre [Label - Texbox]
● Dirección [Label - Texbox]
● Teléfono [Label - Texbox]
● Cargo [Label - Texbox]
● Contacto Emergencia [Label - Texbox]
● Teléfono Contacto Emergencia [Label - Texbox]
● Correo [Label - Texbox]
● IdContratista [Label - Texbox]
● Guardar – Editar – Eliminar – Limpiar – Regresar [Button]

**Comment by NaslyGordi** [comment]
[https://app.zenhub.com/files/244173603/4721c047-1238-41f2-b14a-9a46097c5b41/download](https://app.zenhub.com/files/244173603/4721c047-1238-41f2-b14a-9a46097c5b41/download)
