### ISSUE TITLE
Corrección modelo BD

### ISSUE THREAD

**Issue by TattaArias** [JhonTriana/Poli_CCT#44]
Se realizará actualización y/o modificación del modelo propuesto para la base de datos. Es necesario cambiar a idioma español e incluir lo necesario teniendo en cuenta la observación del Pproduct-Oner en la reunión del sábado 14 de marzo de 2020.

**Comment by javargasgue** [comment]
Nos reunimos para revisar y definir los cambios solicitados, y contemplar las cosas que nos faltaban en el proyecto

**Comment by javargasgue** [comment]
Se sube comedlo a Github para revisión y aprobación
